language: cpp

sudo: required

cache:
  ccache: true
  directories:
  - ${HOME}/.ccache

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

services:
- docker

install:
- pip3 install --user --upgrade "pip>=20.3.4,<21.0"
- pip3 install --user docker-compose

matrix:
  include:
  # - os: linux
  #   dist: xenial
  #   env: BUILD_ARGS='pg docker gcc coverage'
  #   after_success:
  #   - >
  #     docker run -ti --rm -v ${PWD}:/code $(bash -e <(curl -s https://codecov.io/env)) \
  #       ozo_build /codecov.sh

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker gcc debug'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker gcc release'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker gcc test_external_project'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker clang debug'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker clang release'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker clang asan'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker clang ubsan'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker clang tsan'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='pg docker clang test_external_project'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='docker gcc conan'

  - os: linux
    dist: xenial
    env: BUILD_ARGS='docker clang conan'

  - os: osx
    osx_image: xcode11
    install:
    # - brew update
    # - brew unlink python@2
    # - brew upgrade boost
    # - brew upgrade postgresql
    # - brew upgrade cmake
    - brew install ccache
    env: BUILD_ARGS='clang debug'

script: scripts/build.sh ${BUILD_ARGS}
