name: C++ Build

on:
  push:
    branches:
      - main
      - /^[0-9]+-(feat|refactor|fix)-.*/
  pull_request:
    branches:
      - main
      - /^[0-9]+-(feat|refactor|fix)-.*/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt-get install -y build-essential

      - name: Build project
        run: make